### ISSUE TITLE
Example dont compile on cargo 1.29.0-nightly (0ec7281b9 2018-08-20)

### ISSUE THREAD

**Issue by elsuizo** [eupn/efm32hg222f64-hal#2]
Hi!!! first thanks for this repo!!!
I got an error compiling the blinky example:

```
error: Could not compile `emlib`.
warning: build failed, waiting for other jobs to finish...
error[E0557]: feature has been removed
 --> /home/elsuizo/.cargo/registry/src/github.com-1ecc6299db9ec823/efm32hg222f64-0.2.0/src/lib.rs:2:37
#![cfg_attr(feature = "rt", feature(macro_reexport))]
```
I remove this marks in the efm32hg222f64 repo  and I got other errors, I think it's because  the generated code was with an old version of svd2rust
